### ISSUE TITLE
Some games cannot be searched

### ISSUE THREAD

**Issue by Serneum** [ElixirCLE/boardgamegeek_client#6]
```
BoardGameGeekClient.search_games("IncrediBrawl")
** (Protocol.UndefinedError) protocol Enumerable not implemented for "IncrediBrawl"
                  (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
                  (elixir) lib/enum.ex:116: Enumerable.reduce/3
                  (elixir) lib/stream.ex:974: Stream.do_zip_close/1
                  (elixir) lib/stream.ex:947: Stream.do_zip/3
                  (elixir) lib/enum.ex:2468: Enum.zip/2
    (boardgamegeek_client) lib/boardgamegeek_client.ex:31: BoardGameGeekClient.search_games/2
```
See also: Forbidden Island

**Comment by Serneum** [comment]
Potential solution: just retrieve IDs and then make another request to get game data for every ID
